name: Build and Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install cmocka
        run: apt install libcmocka-dev

      - name: Create build directory
        run: mkdir build

      - name: CMake build
        run: cmake -Bbuild -H.

      - name: Make
        run: cmake --build build/ --target all

      - name: Test
        run: ctest
