name: Build and Test
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install cmocka
        run: sudo apt install libcmocka-dev

      - name: Create Build files
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: cmake --build build --target test
